#pragma once

#define        PLUGIN_DATE     20151120
#define        PLUGIN_VERS         0.01
#define        PLUGIN_NAME   "MQ2AFNuke"

// Global Defines
#define NUKESTATE_IDLE 0
#define NUKESTATE_CASTSTART 1
#define NUKESTATE_CASTING 2
#define NUKESTATE_CASTDONE 3
#define NUKESTATE_CASTFAIL 4
#define NUKESTATE_PAUSED 5
#define NUKESTATE_DEAD 6
#define NUKESTATE_ZONING 7
#define NUKESTATE_COOLDOWN 8

#define CASTSTATE_STARTED 0
#define CASTSTATE_TARGETING 1
#define CASTSTATE_CASTING 2
#define CASTSTATE_DONE 3

#define HEALTYPE_SINGLE 0
#define HEALTYPE_GROUP 1
#define HEALTYPE_TANKONLY 2
#define HEALTYPE_BUFF 3
#define HEALTYPE_DI 4

#define TARGET_NO_HEAL 0
#define TARGET_SELF_HEAL 1
#define TARGET_GROUP_SINGLE_HEAL 2
#define TARGET_GROUP_GROUP_HEAL 3
#define TARGET_XTAR_HEAL 4
#define TARGET_PET_HEAL 5

#define MAX_SPELL 128

#define ISINDEX() (Index[0])
#define ISNUMBER() (IsNumber(Index))
#define GETNUMBER() (atoi(Index))
#define GETFIRST() Index
