| This is a macro by Decker, updated by Redbot
| usage:
| /mac chat username

	#turbo
| --------------------------------------------------------------------------------------------
| SUB: Main
| --------------------------------------------------------------------------------------------
	Sub Main
	/plugin mq2irc
	/iconnect irc.esper.net 6667 #redguides ${Param0}
	/delay 12s
	/echo joining #RedGuides channel
	/i join #redguides
	/return
|  [+++  Formatted by MQ2fusing tabs for indents +++]
